#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

log:
  system:
    log_level_default: INFO
    log_levels:
      core: INFO
      net: INFO
      vm: INFO
      storage: INFO
    file_path: ../log/org1/system.log
    max_age: 365                  # 日志最长保存时间，单位：天
    rotation_time: 1              # 日志滚动时间，单位：小时
    rotation_size: 100              # 日志滚动大小，单位：MB
    log_in_console: true          # 是否展示日志到终端，仅限于调试使用
    show_color: true              # 是否打印颜色日志
  brief:
    log_level_default: INFO
    file_path: ../log/org1/brief.log
    max_age: 365                  # 日志最长保存时间，单位：天
    rotation_time: 1              # 日志滚动时间，单位：小时
    rotation_size: 100              # 日志滚动大小，单位：MB
    log_in_console: false         # 是否展示日志到终端，仅限于调试使用
    show_color: true              # 是否打印颜色日志
  event:
    log_level_default: INFO
    file_path: ../log/org1/event.log
    max_age: 365                  # 日志最长保存时间，单位：天
    rotation_time: 1              # 日志滚动间隔，单位：小时
    rotation_size: 100              # 日志滚动大小，单位：MB
    log_in_console: true         # 是否展示日志到终端，仅限于调试使用
    show_color: true              # 是否打印颜色日志
