#
# Copyright (C) BABEC. All rights reserved.
# Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

auth_type: "permissionedWithCert"   # permissionedWithCert / permissionedWithKey / public

log:
  config_file: ../config/wx-org1-solo/log.yml          # config file of logger configuration.

crypto_engine: tjfoc #crypto engine config setting, support gmssl, tencentsm and tjfoc

blockchain:
  - chainId: chain1
    genesis: ../config/wx-org1-solo/chainconfig/bc1.yml
#  - chainId: chain2
#    genesis: ../config/wx-org1-solo/chainconfig/bc2.yml
#  - chainId: chain3
#    genesis: ../config/wx-org1-solo/chainconfig/bc3.yml
#  - chainId: chain4
#    genesis: ../config/wx-org1-solo/chainconfig/bc4.yml

node:
  type: full
  org_id: wx-org1.chainmaker.org
  priv_key_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.sign.key
  cert_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.sign.crt
  cert_cache_size: 1000

net:
  provider: LibP2P
  listen_addr: /ip4/0.0.0.0/tcp/11351
  seeds:
    - "/ip4/127.0.0.1/tcp/11301/p2p/QmcQHCuAXaFkbcsPUj7e37hXXfZ9DdN7bozseo5oX4qiC4"
  #    - "/ip4/127.0.0.1/tcp/11302/p2p/QmeyNRs2DwWjcHTpcVHoUSaDAAif4VQZ2wQDQAUNDP33gH"
  #    - "/ip4/127.0.0.1/tcp/11303/p2p/QmXf6mnQDBR9aHauRmViKzSuZgpumkn7x6rNxw1oqqRr45"
  #    - "/ip4/127.0.0.1/tcp/11304/p2p/QmRRWXJpAVdhFsFtd9ah5F4LDQWFFBDVKpECAF8hssqj6H"
  #    - "/ip4/127.0.0.1/tcp/11305/p2p/QmVSCXfPweL1GRSNt8gjcw1YQ2VcCirAtTdLKGkgGKsHqi"
  #    - "/ip4/127.0.0.1/tcp/11306/p2p/QmPpx5dTZ4A1GQ9a4nsSoMJ72AtT3VDgcX2EVKAFxJUHb1"
  #    - "/ip4/127.0.0.1/tcp/11307/p2p/QmVGSXfz6vgXBjWiZh5rV8T5nutevvunHAfEoe6Sh5Xcyx"
  tls:
    enabled: true
    priv_key_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.tls.key
    cert_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.tls.crt

txpool:
  max_txpool_size: 51200 # 普通交易池上限
  max_config_txpool_size: 10 # config交易池的上限
  full_notify_again_time: 30 # 交易池溢出后，再次通知的时间间隔(秒)

rpc:
  provider: grpc
  port: 12301
  tls:
    # TLS模式:
    #   disable - 不启用TLS
    #   oneway  - 单向认证
    #   twoway  - 双向认证
    #mode: disable
    #mode: oneway
    mode: twoway
    priv_key_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.tls.key
    cert_file: ../config/wx-org1-solo/certs/node/consensus1/consensus1.tls.crt

tx_filter:
  # default(store) 0; bird's nest 1; map 2; 3 sharding bird's nest
  # 3 is recommended.
  type: 0
  # sharding bird's nest config
  # total keys = sharding.length * sharding.birds_nest.length * sharding.birds_nest.cuckoo.max_num_keys
  sharding:
    # sharding size
    length: 5
    # sharding task timeout in seconds
    timeout: 3
    snapshot:
      # serialize type
      # 0 Serialization by height interval
      # 1 Serialization by time interval
      type: 0
      block_height:
        # Block height interval
        interval: 10
      timed:
        # Time interval in seconds
        interval: 10
      # file path
      path: ../data/org1/tx_filter
    # bird's nest config
    birds_nest:
      # bird's nest size
      length: 10
      # Transaction filter rules
      rules:
        # Absolute expiration time /second
        # Based on the number of transactions per day, for example, the current total capacity of blockchain transaction
        # filters is 100 million, and there are 10 million transaction requests per day.
        #
        # total keys = sharding.length * sharding.birds_nest.length * sharding.birds_nest.cuckoo.max_num_keys
        #
        # absolute expire time = total keys / number of requests per day
        absolute_expire_time: 172800
      cuckoo:
        # num of tags for each bucket, which is b in paper. tag is fingerprint, which is f in paper.
        # If you are using a semi-sorted bucket, the default is 4
        # 2 is recommended.
        tags_per_bucket: 2
        # num of bits for each item, which is length of tag(fingerprint)
        # 11 is recommended.
        bits_per_item: 11
        # keys number
        max_num_keys: 2000000
        # 0 TableTypeSingle normal single table
        # 1 TableTypePacked packed table, use semi-sort to save 1 bit per item
        # 0 is recommended
        table_type: 0
  # bird's nest config
  # total keys = birds_nest.length * birds_nest.cuckoo.max_num_keys
  birds_nest:
    # bird's nest size
    length: 10
    snapshot:
      # serialize type
      # 0 Serialization by height interval
      # 1 Serialization by time interval
      type: 0
      block_height:
        # Block height interval
        interval: 10
      timed:
        # Time interval in seconds
        interval: 10
      # file path
      path: ../data/org1/tx_filter
    # Transaction filter rules
    rules:
      # Absolute expiration time /second
      # Based on the number of transactions per day, for example, the current total capacity of blockchain transaction
      # filters is 100 million, and there are 10 million transaction requests per day.
      #
      # total keys = sharding.length * sharding.birds_nest.length * sharding.birds_nest.cuckoo.max_num_keys
      #
      # absolute expire time = total keys / number of requests per day
      absolute_expire_time: 172800
    cuckoo:
      # num of tags for each bucket, which is b in paper. tag is fingerprint, which is f in paper.
      # If you are using a semi-sorted bucket, the default is 4
      # 2 is recommended.
      tags_per_bucket: 2
      # num of bits for each item, which is length of tag(fingerprint)
      # 11 is recommended.
      bits_per_item: 11
      # keys number
      max_num_keys: 2000000
      # 0 TableTypeSingle normal single table
      # 1 TableTypePacked packed table, use semi-sort to save 1 bit per item
      # 0 is recommended
      table_type: 0

monitor:
  enabled: false
  port: 14321

pprof:
  enabled: false
  port: 24321

storage:
#  rebuild_block_height: 5
  store_path: ../data/org1/ledgerData1
  encryptor: sm4    # sm4/aes
  encrypt_key: "1234567890123456" #16 bytes key
  disable_block_file_db: false
#  write_block_type: 0  # 0普通写模式，1快速写模式
#  state_cache_config:
#    life_window: 3000000000000   #key/value ttl 时间，单位 ns
#    clean_window: 1000000000
#    max_entry_size: 500
#    hard_max_cache_size: 10240   #缓存大小，单位MB
#  txexistdb_config:
#    provider: leveldb
#    leveldb_config:
#      store_path: ../data/org1/txexist
  blockdb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/blocks
  statedb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/statedb
  historydb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/history
  resultdb_config:
    provider: leveldb
    leveldb_config:
      store_path: ../data/org1/result
  disable_contract_eventdb: true  #是否禁止合约事件存储功能，默认为true，如果设置为false,需要配置mysql
  contract_eventdb_config:
    provider: sql                 #如果开启contract event db 功能，需要指定provider为sql
    sqldb_config:
      sqldb_type: mysql           #contract event db 只支持mysql
      dsn: root:password@tcp(127.0.0.1:3306)/  #mysql的连接信息，包括用户名、密码、ip、port等，示例：root:admin@tcp(127.0.0.1:3306)/
debug:
  # 是否开启CLI功能，过度期间使用
  is_cli_open: true
  is_http_open: false


vm:
  enable_dockervm: false
  dockervm_mount_path: ../data/org1/docker-go     # mount point in chain maker
  dockervm_log_path: ../log/org1/dockervm
  log_in_console: false
  log_level: INFO
  uds_open: false                             # default is unix domain socket connection
  max_send_msg_size: 20
  max_recv_msg_size: 20
  docker_vm_host: 127.0.0.1
  docker_vm_port: 22359
  max_connection: 1


