{
 "title": "ChainMaker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点名",
    "query": "label_values(chainmaker_committer_metric_block_counter, job)"
   },
   {
    "name": "chainId",
    "label": "链ID",
    "query": "label_values(chainmaker_committer_metric_block_counter, chainId)"
   }
  ]
 },
 "panels": [
  {
   "title": "查询类请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chainmaker_rpcserver_metric_query_request_counter{chainId=~\"$chainId\", job=~\"$node\", state=\"true\"}",
     "legendFormat": "{{instance}}, {{chainId}}, 成功"
    },
    {
     "expr": "chainmaker_rpcserver_metric_query_request_counter{chainId=~\"$chainId\", job=~\"$node\", state=\"false\"}",
     "legendFormat": "{{instance}}, {{chainId}}, 失败"
    },
    {
     "expr": "sum by (instance, chainId) (chainmaker_rpcserver_metric_query_request_counter{chainId=~\"$chainId\", job=~\"$node\"})",
     "legendFormat": "{{instance}}, {{chainId}}, 总请求数"
    }
   ]
  },
  {
   "title": "交易类请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chainmaker_rpcserver_metric_invoke_request_counter{chainId=~\"$chainId\", job=~\"$node\", state=\"true\"}",
     "legendFormat": "{{instance}}, {{chainId}}, 成功"
    },
    {
     "expr": "chainmaker_rpcserver_metric_invoke_request_counter{chainId=~\"$chainId\", job=~\"$node\", state=\"false\"}",
     "legendFormat": "{{instance}}, {{chainId}}, 失败"
    },
    {
     "expr": "sum by (instance, chainId) (chainmaker_rpcserver_metric_invoke_request_counter{chainId=~\"$chainId\", job=~\"$node\"})",
     "legendFormat": "{{instance}}, {{chainId}}, 总请求数"
    }
   ]
  },
  {
   "title": "交易数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chainmaker_committer_metric_tx_counter{chainId=~\"$chainId\", job=~\"$node\"}",
     "legendFormat": "{{chainId}}, {{instance}}"
    }
   ]
  },
  {
   "title": "区块数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chainmaker_committer_metric_block_counter{chainId=~\"$chainId\", job=~\"$node\"}",
     "legendFormat": "{{chainId}}, {{instance}}"
    }
   ]
  },
  {
   "title": "区块大小",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1024\"})",
     "legendFormat": "[0,1024]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2048\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1024\"}))",
     "legendFormat": "(1024,2048]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"4096\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2048\"}))",
     "legendFormat": "(2048,4096]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"8192\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"4096\"}))",
     "legendFormat": "(4096,8192]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"16384\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"8192\"}))",
     "legendFormat": "(8192,16384]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"32768\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"16384\"}))",
     "legendFormat": "(16384,32768]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"65536\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"32768\"}))",
     "legendFormat": "(32768,65536]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"131072\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"65536\"}))",
     "legendFormat": "(65536,131072]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"262144\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"131072\"}))",
     "legendFormat": "(131072,262144]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"524288\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"262144\"}))",
     "legendFormat": "(262144,524288]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1.048576e+06\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"524288\"}))",
     "legendFormat": "(524288,1048576]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2.097152e+06\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1.048576e+06\"}))",
     "legendFormat": "(1048576,2097152]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"+Inf\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_size_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2.097152e+06\"}))",
     "legendFormat": "(2097152,+Inf)"
    }
   ]
  },
  {
   "title": "交易执行时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"})",
     "legendFormat": "[0,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.005\"}))",
     "legendFormat": "(0.005,0.01]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))",
     "legendFormat": "(0.01,0.015]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))",
     "legendFormat": "(0.015,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))",
     "legendFormat": "(0.05,0.1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))",
     "legendFormat": "(0.1,1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_scheduler_metric_vm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "legendFormat": "(1,10]"
    }
   ]
  },
  {
   "title": "wasm执行时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "[0,0.05]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.005\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(0.005,0.01]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(0.01,0.015]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(0.015,0.05]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(0.05,0.1]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(0.1,1]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_wasmer_metric_wasm_run_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "(1,10]",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "交易池交易数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chainmaker_txpool_metric_tx_pool_size{chainId=~\"$chainId\", job=~\"$node\"}",
     "legendFormat": "{{chainId}}, {{instance}}"
    }
   ]
  },
  {
   "title": "区块打包时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"})",
     "legendFormat": "[0,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.005\"}))",
     "legendFormat": "(0.005,0.01]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))",
     "legendFormat": "(0.01,0.015]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))",
     "legendFormat": "(0.015,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))",
     "legendFormat": "(0.05,0.1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))",
     "legendFormat": "(0.1,1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_proposer_metric_block_package_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "legendFormat": "(1,10]"
    }
   ]
  },
  {
   "title": "区块验证时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"})",
     "legendFormat": "[0,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.005\"}))",
     "legendFormat": "(0.005,0.01]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))",
     "legendFormat": "(0.01,0.015]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))",
     "legendFormat": "(0.015,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))",
     "legendFormat": "(0.05,0.1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))",
     "legendFormat": "(0.1,1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_verifier_metric_block_verify_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "legendFormat": "(1,10]"
    }
   ]
  },
  {
   "title": "区块提交时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"})",
     "legendFormat": "[0,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.005\"}))",
     "legendFormat": "(0.005,0.01]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.01\"}))",
     "legendFormat": "(0.01,0.015]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.015\"}))",
     "legendFormat": "(0.015,0.05]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.05\"}))",
     "legendFormat": "(0.05,0.1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.1\"}))",
     "legendFormat": "(0.1,1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_commit_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "legendFormat": "(1,10]"
    }
   ]
  },
  {
   "title": "区块间隔时间(秒)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.2\"})",
     "legendFormat": "[0,0.2]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.5\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.2\"}))",
     "legendFormat": "(0.2,0.5]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"0.5\"}))",
     "legendFormat": "(0.5,1]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"1\"}))",
     "legendFormat": "(1,2]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"5\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"2\"}))",
     "legendFormat": "(2,5]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"5\"}))",
     "legendFormat": "(5,10]"
    },
    {
     "expr": "(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"20\"}))-ignoring(le)(sum by (le) (chainmaker_committer_metric_block_interval_time_bucket{chainId=~\"$chainId\", job=~\"$node\", le=\"10\"}))",
     "legendFormat": "(10,20]"
    }
   ]
  }
 ]
}